name: graduation_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  camera: ^0.11.3
  tflite_flutter: ^0.12.1
  speech_to_text: ^7.3.0
  flutter_screenutil: ^5.9.3
  google_mlkit_text_recognition: ^0.15.0
  flutter_tts: ^4.2.3
  permission_handler: ^12.0.1
  image_picker: ^1.2.1
  path_provider: ^2.1.5
  shared_preferences: ^2.5.4
  image: ^4.2.0
  http: ^1.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true

  assets:
    - assets/models/egypt_currency_model.tflite
    - assets/models/mobilefacenet.tflite
    - assets/models/best_float32.tflite
    - assets/labels/labels_new.txt
    - assets/labels/labels_arabic_new.txt
    - assets/icons/
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#0F2A44"
  adaptive_icon_foreground: "assets/icons/app_icon.png"